### ISSUE TITLE
The Month in WordPress: July 2023 Edition

### ISSUE THREAD

**Issue by eidolonnight** [WordPress/Marketing-Team#266]
### Comment

The Month in WordPress is a monthly roundup of WordPress news, aimed at keeping existing WordPress contributors engaged and updated while also providing an onramp for potential contributors to observe what's happening inside the project. This post is published at the beginning of each month on [WordPress.org/News](https://wordpress.org/news/category/month-in-wordpress/).

## This edition's draft

If you would like to contribute to this edition, please [join us in the Google doc](https://docs.google.com/document/d/13kFvSqeJtRpDXSuS9VAyceOq9ekxHg_bsosoLImjaS4/edit?usp=sharing).

## How you can help

You can help by collecting any news or team updates that would be valuable and relevant to the post. Sources and links to where you can find these updates are included in the Google doc. Please note that, for brevity, it may only be possible to include some links/updates in the final post.

If you have contributed to the doc, please add your name and a link to your WordPress.org profile to the bottom.

## Timeline

The estimated publishing date for the July 2023 edition of The Month in WordPress is **August 11, 2023**. The document will be closed for edits on **August 8, 2023** to allow for final edits and preparation for posting.

**Comment by meherbala** [comment]
**Added to the Doc:** The latest edition of People of WordPress features [Ihtisham Zahoor](https://wordpress.org/news/2023/07/people-of-wordpress-ihtisham-zahoor/) and his inspiring WordPress journey.

**Comment by rmartinezduque** [comment]
The July edition of The Month in WordPress was skipped due to focus on other priorities. The August edition issue is currently open for contributions: https://github.com/WordPress/Marketing-Team/issues/277.

Pinging @chaion07 and @jennimckinnon given your interest in contributing to previous editions. Your input to the August edition (https://github.com/WordPress/Marketing-Team/issues/277) will be appreciated. Thank you!
