### ISSUE TITLE
WordPress.org/news post on the Create Block Theme plugin

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marketing-Team#341]
### Comment

As part of the efforts to talk to [block themers recently via the FSE Outreach Program](https://wordpress.slack.com/archives/C015GUFFC00/p1702356362566639) and in the course of feedback that makes its way to me in various spaces, I've started seeing a need to talk more broadly about the [Create Block Theme plugin](https://wordpress.org/plugins/create-block-theme/). Since it's a community run plugin and is intended to help folks get started with block themes, I think there's a chance here to share what's possible, how the plugin works, and resources to get started. 

What do you all think? What would be most helpful to highlight here? I'll draft something up likely in the coming weeks to get things moving.

**Comment by annezazu** [comment]
Kicked off an extremely rough draft here for anyone who wants to jump in: https://docs.google.com/document/d/1b9MlV9kR6CJm-ierP1Qw7b_8rD9dcGksu2e73qOtm6U/edit?usp=sharing

**Comment by annezazu** [comment]
Alright! Fleshed out the post more so it's a bit coherent. Thinking this can be short and sweet. I'm toying with spinning up a WordPress Playground install to help folks explore it directly and am torn about whether to include a video. Thoughts welcome across the board :)

**Comment by eidolonnight** [comment]
Since this post is targeted more specifically at developers, it seems like it may be better suited to https://developer.wordpress.org/news/ than https://wordpress.org/news/. [A walk-through tutorial on using Create Block Theme plugin](https://developer.wordpress.org/news/2023/12/05/a-walk-through-tutorial-on-using-create-block-theme-plugin/) was also just published though, so I wonder what unique value this might offer.

**Comment by annezazu** [comment]
Yes! That walk through is mentioned in the draft. In my mind, this brings the plugin and what's possible to a larger audience while the Developer Blog is still growing its readership. Since block themes are so important to the ecosystem right now, this would be a pure amplification/awareness building effort through a more high impact channel.

**Comment by annezazu** [comment]
Talking to others, Create Block Theme and Block Themes is also beyond just developers. It allows site builders, designers, and DIY-ers to dive in. It's part of the magic there. Curious to hear from others and am going to tweak the content today to make it more broadly applicable rather than sticking to the term developers.

**Comment by eidolonnight** [comment]
> this brings the plugin and what's possible to a larger audience while the Developer Blog is still growing its readership

We should be careful that we're not just publishing to the News area because of its large audience, and need to ensure that it's the _right_ audience. As we've seen on social, posting to the wrong audience or posting too much can lead to people unsubscribing.

If we're worried about the amplification, that's a relatively easy solve even with this living on the developer blog. We can still promote this across other channels.

> Create Block Theme is also beyond just developers

That is certainly not the vibe given on the plugin page: _"The plugin is development only — not intended for use on production websites"_ The average WordPress user won't even know what a "production" website is, let alone have a development environment.

**Comment by annezazu** [comment]
Okay! Sounds like you're blocking this from moving forward as a dedicated post on /News. Can you move forward with amplification in that case? It's clear we aren't meeting folks where they are here, including builders, designers, and developers.

**Comment by eidolonnight** [comment]
> Sounds like you're blocking this from moving forward as a dedicated post on /News.

Just to clarify, I think the post idea is still a good one! It should just be posted to https://developer.wordpress.org/news/ instead. If that's OK, then we'll want to move this issue to https://github.com/orgs/WordPress/projects/44/views/1.

**Comment by annezazu** [comment]
Closing this out for now assuming we can follow up on amplifying.
