### ISSUE TITLE
Update Marketing Team guidelines to create exceptions for Project Leadership

### ISSUE THREAD

**Issue by sereedmedia** [WordPress/Marketing-Team#347]
As the project leadership has direct posting access to the various official WordPress accounts, I suggest we amend the Marketing Team guidelines to specify that posts directly from project leadership are exempt from the Marketing Team guidelines.

I also suggest we request that whatever the channel, direct posts by project leadership are written in the first person and are signed by the poster, i.e "Support the Bay Bridge Lights in honor of my birthday! - Matt" or "Support the Bay Bridge Lights in honor of my birthday! - MM"

**Comment by bernard0omnisend** [comment]
I believe this is the best way forward to solve this particular issue.

My recommendation (one additional sentence between paragraphs):

"As an open source platform with a team of volunteers, it is important to maintain transparency and fairness for all contributors. As such, it is not appropriate to solicit money or other material resources through the WordPress Marketing channel. This is primarily because there is no fair and transparent way to conduct a fundraising initiative while avoiding conflicts of interest within the team.

The leadership team, who have direct access to the various WordPress marketing channels, are exempt from these guidelines.

Please note that there are a variety of funds and resources available for many areas. You may ask if anybody can direct you to an appropriate place for a request, but cannot fundraise directly with the team through any official channels."

**Comment by Bringmannn** [comment]
> I also suggest we request that whatever the channel, direct posts by project leadership are written in the first person and are signed by the poster, i.e "Support the Bay Bridge Lights in honor of my birthday! - Matt" or "Support the Bay Bridge Lights in honor of my birthday! - MM"

This is a good recommendation. Perhaps, if we're talking about Twitter, a quote tweet? Either would help maintain brand consistency. Here is a past example from State of the Word: https://twitter.com/WordPress/status/1734240337042821303.

> My recommendation (one additional sentence between paragraphs)

A rephrasing for consideration: "Project leadership may choose to make exceptions."
Here's what I changed and why:

- "The leadership team" - This isn't a "team" in the sense that most on Make would consider a team.
- "who have direct access" - Ensuring that their role is identified as what provides exception rather than access. 
- "are exempt from these guidelines" - This isn't an exemption in the sense that someone under these guidelines is being exempted. The guidelines are for those of us who have been delegated a responsibility, not the delegator.

**Comment by bernard0omnisend** [comment]
> "Project leadership may choose to make exceptions."

I think that works. 

It would further mean, then, that they'd choose to make exceptions for themselves, and choose to make exceptions for others. In the original, it implied that those leadership folks who have direct access to the marketing channels have these exceptions, but in this rephrasing the generic identifier of "project leadership" could technically include more folks

**Comment by daveloodts** [comment]
I think there are 2 seperate guidelines here in this.

The surprised one is: "The Leadership team is owner of the social channels and is allowed to post whatever they want, also without approval of the related teams such as Marketing, ...)


The original guideline was about "money" and "material". And i don't think the guideline should even mention those words. If it's flatlined like this, it brings more limitations on the table, then opportunities for the Marketing team.

Matt's reply on my question:  is it allowed for the Marketing team to do campaigns about donating for the project (via Foundation) or Open Community Collective?

Matt: "_it would be great if marketing did campaigns for those two things, the donors list for the Foundation is pretty anemic:_"

So, great news, right! That is a nice goal to have for a Marketing team.

In fact, Jenni jumped in and explained me the reason about the rule. Which is mostly denying requests of WordCamp or Meetups for their Call for Sponsors. I was main organizer of 2 WordCamps back in 2016 and 2018, meetup +80 editions, if you have common sense as an organizer, you know that's impossible that the WP social channels make calls for that.
But okay; guidelines must be clear.

So, that guideline could be: The official social media channels of wordpress.org can't be used for call for speakers/organizers/sponsors, except WCUS, WCEU and WCASIA.

That's all this guideline would be saying about the "donation" topic. 

If you mention the word "no fundraising" then you would still have a problem. You know: a bridge has 2 sides. I don't know if the Bay Light campaign was for one side or not. (LOL: was a joke right, we could drop some tensions here). 
I just mean: if you put words into guidelines, and leadership jumps over it, just a recipe for another wpdrama.

So, i"m a fan of making things simple and clear, and be as precise as it can be in simple terms. 

_By the way: i'm also a fan of Jenni!
Jenni, i like you communication-style: clear, concrete, to the point but still open and always welcoming. The way how you handled the issue the last couple of days is amazing. The Leadership team can learn a lot from you.__

**Comment by alexstine** [comment]
Agreed with everything here. Clear written guidelines benefit everyone.

**Comment by gusaus** [comment]
Are these [the guidelines](https://make.wordpress.org/marketing/handbook/resources/fundraising-policy-for-wordpress-contributor-teams/) we're trying to clarify? If yes, it's also confusing the "Fundraising Policy for WordPress Contributor Teams" (assuming that means all teams listed on https://make.wordpress.org/) is a bit hard to find unless you know where to look.

**Comment by eidolonnight** [comment]
@bernard0omnisend and @Bringmannn 's recommendation seems simple and sound for the Marketing Handbook:

> Project leadership may choose to make exceptions.

The remaining questions regarding general fundraising practices for the project, and possible campaigns, seem best suited to new discussions, possibly within the Sustainability team. For now, I think the team reps can apply the recommended edit and consider this closed.

As for some of the other marketing questions, I think that I can answer those quickly:
- A call to raise interest in the WordPress Foundation has always been considered within these guidelines given its relationship to the WordPress project. Announcements from [WordPressFoundation.org/news/ ](https://wordpressfoundation.org/news/) have been shared across social accounts in the past.
- For additional notes on the approach to amplifying WordCamp announcements, please read [Discussion: Promoting WordCamps with the official WordPress social accounts](https://make.wordpress.org/marketing/2022/06/17/discussion-promoting-wordcamps-with-the-official-wordpress-social-accounts/).
- The guidelines in the Marketing Handbook apply to the Marketing Team contributors in our efforts to promote the project. That would include content shared with the team by contributors to other teams (typically through [the Request for Amplification form](https://github.com/WordPress/Marketing-Team/issues/new/choose)).

**Comment by bernard0omnisend** [comment]
I've updated this now to include the recommended sentence. 

The other discussions deserve their own issues

**Comment by sereedmedia** [comment]
Thanks @bernard0omnisend, that sentence at the very least makes it clear that Project Leadership is exempt from the guidelines. 

It does not clarify how anyone would know if Project Leadership has made an exception, but as you said, that is a separate discussion.

Closing this issue as the update has solved the immediate conflict of the WordPress social media accounts being used outside of the guidelines.
