### ISSUE TITLE
Trac ticket commenting & bug raising training for non-tech members

### ISSUE THREAD

**Issue by murillol** [WordPress/Marketing-Team#35]
**Done**: Delivery of sessions to help non-dev members of the team be able to comment on trac tickets (for WordPress)/ GitHub (for Gutenberg/ editor) tickets and to be able to raise bug reports particularly in the Block editor.

**Deadline**: TBD

**Task**:
- Help with how to raise a bug ticket and comment on trac from non-dev members of the team to help them participate in influencing tickets and understanding core and releases
- This in turn helps with marketing those areas and creates a better understanding of open source and the development of WordPress to be able to market it better and communicate it more effectively

_Objectives and outcomes (initial scope)_:
- To work with core to create an informal screen share-based two sessions (to reflect timezones) aimed at non-developers in the team
- Check what resources already available on this from core and training teams, and if they could be adapted to meet the needs of non-developers in the marketing team
- The sessions to be hands-on where members of the team could practise the steps as the current resources have not been sufficient to help some of the non-developer members who have been trying to increase their knowledge in this area to be able to contribute to future release marketing
- To cover basic ability to comment on trac tickets (for WordPress)/ GitHub (for Gutenberg/ editor) tickets and to be able to raise bug reports particularly in the Block editor.

*Timeline*:
**23 July 2020**
Slack Discussion: https://wordpress.slack.com/archives/C0GKJ7TFA/p1595499485420200

Timescale:
- implementation in time for contributors in the team to be able to bug test for the 5.6 release.

Requests out to:
- Jon Bossenger to help with this and co-ordinate next steps from this card
- @vimes1984 to assist linking it with other dev marketing work being scoped

Team Rep setting up card: @abhansnuk 

Note to all who have provided feedback into this so far: Thanks everyone for being willing to try out new features and for raising queries. All the questions have been important and together we make an even better WordPress.

**Comment by abhansnuk** [comment]
30/3/2022 Shared with Chris in Slack for potential to share with contributor events coming up

**Comment by abhansnuk** [comment]
This has moved on last year. This is now something that can be done with training and core, and potentially tested by non devs in marketing and training. 

Since this task was created, discussions have led to the following Learn WordPress resources being created to address some of this:
How to use Trac
[How to use trac](https://learn.wordpress.org/workshop/how-to-use-trac/)

Lesson Plan - local install
https://learn.wordpress.org/lesson-plan/local-install/


There are also resources that were put together for WCEU 2021 which have been further developed aimed at Learn WordPress which are related to this, eg set up a testing environment. Some of these were published on [WCEU Contribute core section](https://europe.wordcamp.org/2021/contribute-to-wordpress/core-team/), others are in the google drive for potential review and use in Learn WordPress at a later date.

In addition, in [5.9, a guide to help testing](https://make.wordpress.org/test/2021/11/30/help-test-wordpress-5-9-features/) was created in core, which is on a core post, but could be moving to Learn WordPress as generic information.

Some core team members have also offered to be involved in a video support session to help non-tech members in training, marketing and documentation members in understanding how to find, comment, and raise a bug on trac.

There is also cross-team collaboration planned on a session to help contributors from these teams with releases and for 6.0 there will be a walkthrough of features on 5 April 2022. 

This ticket will be reshared with training to see if it will better sit there as part of resources created for Learn WordPress. Links to materials when available can then be added to the marketing handbook, where relevant.

@courane01 @azhiya

**Comment by azhiya** [comment]
I think it makes sense to move the content to Learn and have the links added to the handbook.

**Comment by azhiya** [comment]
Noting that Courtney has changed her handle to @courtneyr-dev

**Comment by eidolonnight** [comment]
@azhiya thanks for jumping in. Before we close this issue, is there somewhere we should follow the progress of this or anything you would like the Marketing Team to assist with?

**Comment by abhansnuk** [comment]
This needs to be left available on the board so post release work, it can be migrated to Learn WP. It does not need to be open as a marketing task.
