### ISSUE TITLE
[AMPLIFY]: Power in the Details Core Editor Improvement Post

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marketing-Team#369]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

None/Not sure/Other

### MakeWP Team

Core

### What do you want to amplify?

Share a post about features coming up in WordPress 6.5

### Amplification request details

Happy to pass on any of the videos I made in case you all want to re-use them.

### Links

https://make.wordpress.org/core/2024/02/10/core-editor-improvement-power-in-the-details/

### Deadline

Sometime in the next 1-2 weeks.

**Comment by annezazu** [comment]
Here you go! 

https://github.com/WordPress/Marketing-Team/assets/26996883/ff74cca8-05a4-4bc6-af7d-0fc08e8bb520


https://github.com/WordPress/Marketing-Team/assets/26996883/ad46a8e2-0a7d-4edf-9e35-4ea8778db0a0


https://github.com/WordPress/Marketing-Team/assets/26996883/9c679b4f-ff68-4be8-ac2a-80e87fcc6090


https://github.com/WordPress/Marketing-Team/assets/26996883/ea42ee26-c8e3-4fd6-96ed-7bbbbe245674

Happy to review the tweets too.

**Comment by rmartinezduque** [comment]
Thanks, @annezazu! I drafted the copy for the social posts in [this document](https://docs.google.com/document/d/11KfuvSUOXpGb7D_kH8-uPGA2yRm5JDf70_0dWbCd3_Q/edit), along with links for each image and video. Please feel free to have a look to ensure everything feels ok and accurate. Note that tweets are limited to 280 characters, so I don't go into a lot of detail or other specific improvements for some of them. I've also omitted the Preferences panel and support for Cover block aspect ratios from having its own tweet. Not for any particular reason, just not to make it longer and see how it goes since we haven't tried this format before. In any case, I added a link to the post at the end of the thread for more details. Thanks!

**Comment by annezazu** [comment]
Reviewed! Thanks so much for diving in here. This is looking really cool.

**Comment by rmartinezduque** [comment]
@bjmcsherry the copy for the social posts, along with the visual assets, are ready to be posted.

**Comment by rmartinezduque** [comment]
The posts are live. 🎉 Please help share and amplify:

- [X/Twitter thread](https://twitter.com/WordPress/status/1760685634157719696)
- [LinkedIn](https://www.linkedin.com/posts/wordpress_core-editor-improvement-power-in-the-details-activity-7166483035473850368-fuGY/)
- [Facebook](https://www.facebook.com/WordPress/posts/pfbid02Vxk4BDBWpApPfoEvaDeAcL6A3pbFfJ48Sh55pXstY4VQ39TFuNE1fi1HfDXpWWvhl)

This is the first time we tried the thread format to promote the post on X/Twitter. @bjmcsherry and I ran into a few issues while he shipped the tweets via Sprout. For example, it didn't let us add videos to tweets, and we couldn't add alt text to images either. The tool was also a little fussy when it came to sending separate replies. But overall, we considered it a great test to learn what Sprout allows and doesn't allow.
