### ISSUE TITLE
Marketing Team Reps nominations, elections and confirmations for 2023

### ISSUE THREAD

**Issue by abhansnuk** [WordPress/Marketing-Team#38]

**Comment by nalininsbs** [comment]
If you are a contributor who raised interest in standing for 2023, you can add your interest on this card.

**Comment by nalininsbs** [comment]
Every person in the team, irrespective of what timezone or country they live or work in, can express an interest in standing for team rep in 2023.  Team rep nominations for 2023 can come from anyone in the team, a contributor should not feel they have to stand because they are nominated. Their listing on a shared list to be checked with them before publishing. Some contributors indicated that they may consider standing in 2023. Even if  who did not express an interest previously, contributors are very welcome to put themselves forward. 

The shared [list](https://docs.google.com/spreadsheets/d/1_LilfZk9wifOmYquR9JTgOARCFFh2HJS9zY4qPrkA58/edit#gid=0) of those interested in or nominated to stand for 2022. I am sharing this again in case anyone listed, who had indicated them they may consider in 2023, would still like to consider standing. There is no pressure from previous indication to stand. As shown in 2022, the first column is for those who were put forward. It does not mean they were happy to stand.  (@Meher and @abhansnuk can you please recheck this link is no longer editable and put Larissa's name into the right color to reflect 2022 updates).

I have a new sheet draft for 2023 using similar headings I will check fields work with Meher who has previously assisted me with these spreadsheets due to accessibility of the tool. This can then be added to this card. 

As part of process, I have a working draft of post, will share.  When message in team reps group appears for all teams in 2023, we should add it to this card and in the draft post.

Current team reps started in February, with two initially aimed at a job share, this has in reality involved contributing a whole role each, and all three reps working together as a group of three and supporting each other to assist the team. 

For the draft post, to confirm timetable. Primarily if new team reps term will start at end of January to provide for 2023 an overlap and support due to later start of the 2022 term? This will depend on the willingness and expectation of 2022 reps to be available until what date. Elections in December are tricky due to people's commitments. 

**Draft timetable**
September/ October: start considering 2023 encouragement
November: share GitHub card and a draft post/ post as part of an agenda in the weekly meeting to encourage interest. Include process information given to all teams in Team Reps group (not yet showing in team reps group)
December: elections/ nominations? This could be January for 2023 with the later start of 2022 reps, depending on their availability.
Start period: end of January 2023?
Thank you post and new team reps post: January 2023
Opportunity for Marketing team annual get together online/ event: January/ February 2023

This is all planning and to help encourage contributors in 2023 and those coming into the team who may want to think about the following year too. This can help with sustainability and forward planning too. Thank you.

**Comment by eidolonnight** [comment]
I've copied the sheet for 2022 into a new 2023 sheet: https://docs.google.com/spreadsheets/d/1_LilfZk9wifOmYquR9JTgOARCFFh2HJS9zY4qPrkA58/edit#gid=2085252805

I've also added a column for pledge status. We discussed last year the benefit of having a mix of self-sponsored and sponsored contributors acting as team reps, and I think that has served us well several times in 2022.

I also wanted to share last year's nomination post: https://make.wordpress.org/marketing/2021/11/22/2022-team-nominations-for-marketing/

**Comment by nalininsbs** [comment]
Last week I contacted Chloe for timescale or link to any announcements and arrangements on 2023 team rep nominations. This is to link to the post for 2023 in marketing and to be able to follow across teams a same approach.  

Josepha has commented that there will be a post shortly.

**Comment by nalininsbs** [comment]
The [draft post](https://make.wordpress.org/marketing/?p=10316&preview=1&_ppp=83e9cd534f) is now on the Marketing blog, with a slightly updated timetable so we can have nominations and elections in 2022 itself. If useful,  the spreadsheet itself can be added on the blog after publication of the post to avoid it going out as an attachment in the RSS feed as it lists names. 

Once the post is published, this card will be updated with a summary of the nomination process and a link to the spreadsheet. 

The post needs to be published by tomorrow and be included in the agenda for this week's meeting. This card will also be shared in the marketing slack as part of the usual reminder for this week's meeting.

**Comment by murillol** [comment]
Thank you @nalininsbs! I think the post looks good, and that: 

- we should allow people to leave nominations in the post comments or directly in the sheet. 
- stating the min. weekly time commitment is good so people know what to expect can be helpful

**Comment by nalininsbs** [comment]
The [2023 nomination [](post](https://make.wordpress.org/marketing/2022/11/16/2023-team-rep-nominations-for-marketing/)) was published on November 16, 2022.  The timetable was finalized after the global team meeting to allow for  additional comments there, and on the card. 

The article was shared in threads and main marketing channel, and in the team reps channel for inclusion in newsletters. It will be highlighted in the reminder for the agenda on Slack on November 22 and in the global meeting on November 23, 2022.

**Comment by nalininsbs** [comment]
Reminders in slack chat and during meetings. 

Latest reminder 2022/11/29 - https://wordpress.slack.com/archives/C0GKJ7TFA/p1669750087641839

**Comment by nalininsbs** [comment]
Nominations closed at 09:00 UTC on December 6, 2022.
The post updated with nominations close. **Once final list of those going forward confirmed and election link available, post to be updated again..** 
Request sent to [team reps group on Slack](https://wordpress.slack.com/archives/C023M4VELMB/p1670415497443609) for elections form to use.
Script updated suggested for meeting.

Nominations by deadline: WordPress IDs nalininonstopnewsuk, webcommsat, robinwpdeveloper, santanainniss, sereedmedia.
Note: nominees to confirm they are happy to stand before entered on election form.

One nomination received today by direct message on December 7, 2022, after deadline for nominations closed. Encouraged for nomination to stand for 2024. 

If in the event of the team not having two people who have been nominated willing to stand for 2023, can we put the late nomination forward for the election?

**Comment by nalininsbs** [comment]
I am looking at updates on nominations and with the other team representatives in marketing. This needs progress by the team. The discussion on elections tools in team reps slack. Poll.fm is used by many teams. Request was sent to the other team reps on whether there was a shared account which could be used. Pooja from Training shared Learn WordPress Poll.fm account was used for training. Note training has raised there has been an issue on votes not appearing from certain areas. 
Asked the other marketing team reps on whether they had [poll.fm accounts](https://wordpress.slack.com/archives/C023M4VELMB/p1670432227155099?thread_ts=1670425583.821269&cid=C023M4VELMB) which could be used etc 8 December 2022. 
For reference, training poll update 10 December 2022, re [poll.fm](https://wordpress.slack.com/archives/C023M4VELMB/p1670593116295449)

**Comment by nalininsbs** [comment]
[Discussion thread ](https://wordpress.slack.com/archives/C0GKJ7TFA/p1670426686263109)raised at last week's meeting on number of nominations. I have added the representative count from other teams I could find.

**Comment by nalininsbs** [comment]
For completeness, information from Slack, site and GitHub elsewhere.

Nominated by team members (WordPress.org IDs below) on the post by the deadline:
- webcommsat, santanainnis, robinwpdeveloper, nalininonstopnewsuk, sereedmedia

Discussion on whether there should be two or three team reps for 2023 in Slack and highlighted on GitHub above.

Nominees who accepted the nominations for consideration for 2023:
- santanainnis, robinwpdeveloper, sereedmedia

No election/ poll held as three reps suggested for meeting on 21 December 2022. 
Confirmed:  santanainnis, robinwpdeveloper, sereedmedia will be team reps for Marketing for 2023, starting on 1 January 2023. 

All three asked to send details of WordPress contribution, photo, short bio for the post welcoming 2023 reps and thanking 2022 reps and contributors. Reminders sent, note holiday period coincides.

Note: global WordPress Marketing meeting time and possibly day will change in 2023 as not all the 2023 team reps can make Wed 15:00 UTC. This will be discussed and set with the team in 2023.

**Comment by nalininsbs** [comment]
I am adding a list of team rep page to be updated and checklist for help onboarding new teams reps on GitHub for update.
- updated the team reps handbook page with the updated content from the team rep elections, and the GitHub checklist
- more steps to add in from information shared with 2023 team reps in the last week. Checklist to be attached when finished to GitHub card for 2023 and 2024 to make it easier for future and less work.
-

**Comment by abhansnuk** [comment]
[Meta request](https://wordpress.slack.com/archives/C02QB8GMM/p1673299324101619) updated with adding here access for 2023 marketing team reps.

**Comment by abhansnuk** [comment]
**Marketing blog P2 access:**
- @nalininsbs added/ upgraded access for Robin and Santana, and sent Se an invitation to join. 
- @abhansnuk resent invitation and added Se. Tested. Works.

Marketing P2 homepage updated with new time for global Marketing Team meeting: Tuesday 15:00 UTC to help Se.
https://make.wordpress.org/marketing/ 
Temporarily added the first meeting time to avoid changing the relative time shortcode as it is picked up in other places on the website. **To do:** The first meeting date can be removed after 10 January 2023.

**Comment by abhansnuk** [comment]
@nalininsbs sent a [Meta ticket](https://meta.trac.wordpress.org/ticket/6668#ticket) for an update request for the homepage of Make WordPress to the new meeting date and time for 2023. I have included that the first meeting that the first meeting will be on January 17, 2023.

**Comment by abhansnuk** [comment]
Handbook and Team Reps pages:
- 2023 marketing team reps added to https://make.wordpress.org/marketing/handbook/about/  @nalininsbs I have resolved the query on the accent on the name
- Team Reps page in Marketing Handbook - link to list of current team reps added. https://make.wordpress.org/marketing/handbook/getting-involved/teamrep-handover/
- Team Reps, main website, all links now working

New time and date for meetings added to:
- homepage of marketing
- [about page](https://make.wordpress.org/marketing/handbook/about/#when-does-the-global-marketing-team-meet)

**Comment by sereedmedia** [comment]
All new team reps onboarded and 2023 year in progress!
