### ISSUE TITLE
WordPress.org/News post about Performance improvements

### ISSUE THREAD

**Issue by annezazu** [WordPress/Marketing-Team#381]
### Comment

While we have some lovely in depth articles about performance improvements from the Performance Team, we don't have a ton of more broadly applicable performance posts talking about and highlighting our advances to a more general audience. I've tried a few below:

https://make.wordpress.org/core/2021/03/04/core-editor-improvement-need-for-page-post-speed/
https://make.wordpress.org/core/2023/04/05/wordpress-6-2-performance-improvements-for-all-themes/
https://make.wordpress.org/core/2021/03/23/core-editor-improvement-performance-matters/

In my mind, we could do a tidy news post talking about dedicated focus on performance, performance team, and highlight some big improvements in plain language. For folks who want to learn more, we could then link off to efforts like https://make.wordpress.org/core/2023/12/19/wordpress-performance-impact-on-core-web-vitals-in-2023/ that dig into more technical implications.

I'd love to work alongside someone in the performance team on this so I'll drop this into their channel too ✨

**Comment by felixarntz** [comment]
I'd love to collaborate on this!

You mention in the [Slack thread](https://wordpress.slack.com/archives/C02KGN5K076/p1708538746339319) that it would be great to get this out in April, which would work great for me. Just a heads up that I'll be going for (more) baby bonding leave on April 15, so preferably we can wrap it up before then. But even if not, the rest of the performance team would still be able to get it across the finish line :)

**Comment by annezazu** [comment]
🥳 Amazing! Let's do it. From the slack thread, it sounds like the Performance Team can kick this draft off and run with it. I'd love to help review _and_ can also write the draft if that's easier. Game for whatever and really excited about this. It's about time we had a News post!

**Comment by annezazu** [comment]
Noting that a draft has been done by @felixarntz [here](https://docs.google.com/document/d/1Gw3WTTOkHL4tn8lQCO5uaI_kUTFUGbpaECZNLh-aVg8/edit?resourcekey=0-8avzCIzaeblO6119ck-2bA#heading=h.kz2st2186nt) with reviews from myself, @joemcgill, and Peter Rubin (editor). I'm working to see if I can get a designer to help with a proper featured image.

**Comment by felixarntz** [comment]
Thanks @annezazu. Based on the draft feedback I think it's good to go, so I could move it to a .org draft. Will await your input for the next steps.

**Comment by annezazu** [comment]
@DanSoschin said he can dive in tomorrow! 🥳

**Comment by DanSoschin** [comment]
Taking a look from an editorial and WordPress voice standpoint. Will post back here once complete.

**Comment by felixarntz** [comment]
Thank you @DanSoschin! I have created a [public version of the draft](https://docs.google.com/document/d/1X9LsbPlMie0dggY33yrpNvCKJa53ZtXO013-Wj2pS-s/edit) for further review.

**Comment by annezazu** [comment]
With lovely help from Joen, [have a featured image template we can use in figma](https://www.figma.com/file/0TEsQTGMdgaWJYBGHBYP81/Untitled?type=design&node-id=0-1285&mode=design&t=mwkuqhtaBZmBGU6n-0). Here's what I have for now:

<img width="1080" alt="How WordPress is creating a faster web featured image" src="https://github.com/WordPress/Marketing-Team/assets/26996883/b4f0fbd9-b609-4f8e-91b8-ba8a5961c497">

**Comment by DanSoschin** [comment]
Okay, I've shared my suggestions in the doc. Excited to see this ship!

**Comment by annezazu** [comment]
Updated featured image to match casing!

<img width="1080" alt="How WordPress is Creating a Faster Web" src="https://github.com/WordPress/Marketing-Team/assets/26996883/4adf5089-916f-49d1-ab18-d1dd37f60571">

**Comment by felixarntz** [comment]
@DanSoschin Thank you for all your suggestions on the doc! I went over them and applied most, and followed up on the others. Can you please take another look?

**Comment by DanSoschin** [comment]
Looks good... I agree with most of your comments and clarified a few of my own...

**Comment by felixarntz** [comment]
Thank you @DanSoschin, made a few more updates based on your responses. Ready for another look! 👍

**Comment by DanSoschin** [comment]
It's great! Thanks for including me on this.

**Comment by annezazu** [comment]
@DanSoschin when can we get this shipped? Would love to see it out there asap.

**Comment by DanSoschin** [comment]
Ah, I didn't not realize ya'll were leaning on me to ship. Happy to do that. @felixarntz, just let me know and I'll move this to the CMS and provide a preview link. From a timing perspective, that will likely be Friday. If that's okay, great. If you want to ship on Monday, I am happy to do that as well. If you don't need me to ship and want to yourself, that's fine too!

**Comment by felixarntz** [comment]
@DanSoschin I'm happy to put this draft up to .org shortly. Haven't done it before on that blog, so let's see if I'm successful. I'll share a public preview link.

**Comment by felixarntz** [comment]
Here's the public preview: https://wordpress.org/news/?p=17208&preview=1&_ppp=e3ef4b7e83

@annezazu Can you add the featured image to the post please?

Regarding publishing, what date & time would you recommend?

**Comment by DanSoschin** [comment]
You'll get more views if you publish on Monday than on Friday, typically.

**Comment by annezazu** [comment]
I fear I don't have the permission level to add it! I'll DM you with the file.

**Comment by felixarntz** [comment]
@annezazu Thank you, added to the post!

**Comment by annezazu** [comment]
Do it! Sounds perfect. I'll be out next week so no blockers from me.

**Comment by felixarntz** [comment]
Published: https://wordpress.org/news/2024/04/how-wordpress-is-creating-a-faster-web/

Is there anything else that is typically done as part of new posts? Otherwise, this can probably be closed. 🎉

**Comment by DanSoschin** [comment]
That's basically it... in theory, you could open an amplification request to get some posts on social media, but I can do that for you... I'll get the post shared this week!

**Comment by eidolonnight** [comment]
Hi, everyone. Following up here with some notes from this recent post.

Posts to WordPress.org/news automatically generate email notifications, and in this case the email generated from [How WordPress Is Creating a Faster Web](https://wordpress.org/news/2024/04/how-wordpress-is-creating-a-faster-web/), landed in spam (flagged for possible phishing) for two of my Google accounts and generated a security alert for one that I admin. I've confirmed that this has happened for several other folks as well.

My suspicion is that one of these paragraphs was the problem:

> Additionally, the new [WordPress plugin checker](http://wordpress.org/news?action=user_content_redirect&uuid=c89426b926a6d39fd265f6134c6d905b79831399d1d68046c6169a6d439fefc6&blog_id=14607090&post_id=17208&user_id=0&subs_id=641447348&signature=84b8a25d9eeccb517a879e950eb94506&email_name=new-post&user_email=atesterfordotcom2@nicholasgarofalo.com&encoded_url=aHR0cHM6Ly93b3JkcHJlc3Mub3JnL3BsdWdpbnMvcGx1Z2luLWNoZWNrLw=) allows checking any plugin for performance best practices, among other requirements and recommendations. The plugin checker should lead to more performance awareness in plugin authors and, eventually, faster plugins. If you develop plugins, consider integrating this tool into your development and testing workflow.
[...]
WordPress contributors are determined to continue this trend by working on further performance iterations. Whether you’re a WordPress end user, administrator, site builder, or developer, you can contribute to this effort. Anyone can test the performance features before being released in Core through individual feature plugins. Each feature can be tested via the [Performance Lab plugin](http://wordpress.org/news?action=user_content_redirect&uuid=faf8a6d513eded5f931e7ed600253d43a7a8ffc079872539774f78d473f1d2fb&blog_id=14607090&post_id=17208&user_id=0&subs_id=641447348&signature=ea68c3d33c5cfb2bffdc5cee01ca4b30&email_name=new-post&user_email=atesterfordotcom2@nicholasgarofalo.com&encoded_url=aHR0cHM6Ly93b3JkcHJlc3Mub3JnL3BsdWdpbnMvcGVyZm9ybWFuY2UtbGFiLw=), so please try them! Testing features early helps the team assess their impact and collect valuable feedback.

Not long ago, we published [Alert: WordPress Security Team Impersonation Scams](https://wordpress.org/news/2023/12/alert-wordpress-security-team-impersonation-scams/) where we say _"The WordPress Security Team will never email you requesting that you install a plugin or theme on your site..."_ But here is a very official-looking email asking folks to install rather vague plugins to improve their site health and performance. To Google's AI, this probably looked similar to various phishing emails they've identified in the past.

Tone likely played a role as well. I can see, and ChatGPT agrees, that this post was written in a persuasive, encouraging, and informative tone. Meanwhile, beta release posts register as strictly informative and instructive, and they do not typically trigger these sort of filters.

In order to avoid this issue with future performance posts, I recommend the following:
1. Where possible, avoid asking readers to install plugins. If necessary, do so in a strictly informative tone (i.e. avoid phrases like "please try them!").
2. When writing about performance, lean into an informative or educational tone. Run your draft through ChatGPT or something else for tone detection. If any of it registers as encouraging or persuasive, consider re-writing.

From a marketing standpoint, I can understand why we would want to excitedly deliver performance messaging. If we let the numbers speak for themselves, we should be able to do so while also maximizing deliverability.

**Comment by annezazu** [comment]
Yes! Let's close.
