### ISSUE TITLE
[AMPLIFY]: WordPress Kerala Photo Festival 2024 Event Success

### ISSUE THREAD

**Issue by askhellosatya** [WordPress/Marketing-Team#385]
### What is the goal of this amplification request? (select all that apply)

Inform community/make an announcement (no action necessary)

### What is the intended audience(s) for this content? (select all that apply)

Any/All/Don't know

### Are there any specific platforms where you would like this to be shared? (select all that apply)

Any/All/Don't know

### Campaign

#WPPhotos

### MakeWP Team

Community, Marketing, Openverse, Photos

### What do you want to amplify?

WordPress Kerala Photo Festival 2024 Event Success

### Amplification request details

I suggested the following copy to share the latest next-gen event's impact in the WordPress Photo Directory:

> 📸 Experience the stunning captures from WP Kerala Photo Festival 2024! Dive into the remarkable collection of 1544+ photos by 160+ contributors in just 7 days: https://bit.ly/wpkeralaphoto🌟 Share your best shots and help enrich the WordPress photo directory! 🎉 #WPKeralaPhotos
[photo](https://wordpress.org/photos/photo/54765bdde1/) by muktharea

### Links

https://wordpress.org/photos/t/wpkeralaphotos/

### Deadline

N/A

**Comment by rmartinezduque** [comment]
This is a great starting point. Thanks for sharing, @askhellosatya! A few notes that we might want to consider:

> Experience the stunning captures
> Dive into the remarkable collection
> Share your best shots

I feel this encourages many actions without being 100% clear on the main call to action. The adjectives and superlatives used in the copy also express a high level of enthusiasm and exceptionalism, in my opinion. This is not a bad thing, but I think we can convey a similar positive message without being overly enthusiastic in our writing and thus be more on point with the [WordPress Brand Writing Style Guide](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#voice).

Here's another suggestion that can help address the above points:

> Thank you for making the WordPress Kerala Photo Festival a big success! 🎉 Over 1500 photos from 160+ participants were submitted to the Photo Directory, contributing to the growth of this openly licensed image library. Enjoy them all at wordpress.org/photos/t/wpkeralaphotos/ #WPKeralaPhotos

Regarding the photo credit:

> [Photo](https://wordpress.org/photos/photo/54765bdde1/) by muktharea

This may have to be omitted in X/Twitter because of the character limit. But it can be included on other platforms, such as LinkedIn, Facebook, or Instagram. Either way, I usually suggest including it in the alt text to ensure photos are credited. For example: _Five children running and playing on the seashore with the sun setting behind them and their silhouettes reflecting on the sand. Photo contributed by muktharea to the WordPress Photo Directory._

Hope this helps!

**Comment by askhellosatya** [comment]
It's a great copy, @rmartinezduque! I've included it to ensure we not only celebrate the success of this event but also encourage the audience to contribute to the WordPress photo directory. However, you're right. 

I'm suggesting another copy for review, perhaps it can cater to both with clarity.

> 🙏 Thank you for making the WordPress Kerala Photo Festival a big success! Explore 1544+ photos contributed by 160+ talented individuals here: https://bit.ly/wpkeralaphoto Share your best shots to enrich the WordPress photo directory! #WPKeralaPhotos [Photo](https://wordpress.org/photos/photo/54765bdde1/) by muktharea 📸🌟
> 
> Image alt: _Five children running and playing on the seashore with the sun setting behind them and their silhouettes reflecting on the sand. Photo contributed by muktharea to the WordPress Photo Directory._

If it looks good, then it's great; otherwise, the copy you shared is good to go.

**Comment by rmartinezduque** [comment]
Thank you, @askhellosatya, and sorry for the delay. That copy looks much better! I still see a few minor things (I'm noting them here so we all can learn).

The first one is regarding the use of emojis to stay closer to the [recommended guidelines](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#social-media). They are usually optional and, in case we want to include them, I think having one or two at the most is fine.

On the other hand, since there is no obvious transition or connection between the success of the event and encouraging contributions to the directory, I feel that the sentence "Share your best shots..." might be confusing (it may seem that the festival is still open for submissions). Maybe I'm overthinking here 😄 but with a slight edit that could feel clear:

> Thank you for making the WordPress Kerala Photo Festival a success! 🎉 Explore more than 1500 photos submitted by 160+ talented individuals—and keep your contributions to the Photo Directory coming. wordpress.org/photos/t/wpkeralaphotos/ #WPKeralaPhotos

**Comment by askhellosatya** [comment]
Hi @rmartinezduque, thank you for bringing that to my attention. I'll be mindful of emoji usage in the future. The draft looks great, and it seems ready to go.

**Comment by bjmcsherry** [comment]
These have been scheduled to launch tomorrow at 8:15 pm UTC. If you are able to, please remember to look at our social channels and share. I will close the ticket with this post.
