### ISSUE TITLE
[SHOWCASE]: https://www.rapyd.net/

### ISSUE THREAD

**Issue by bernard0omnisend** [WordPress/Marketing-Team#429]
### Submission ID

202310230911410

### Site URL

https://www.rapyd.net/

### Submission date

23 Oct 2023

### Submitter

Miriam Schwab

### Author

WPExplorer

### Theme

Total

### Launched On

1 Oct 2022

### Country

Israel

### Description

Rapyd is the global fintech partner that simplifies and advances commerce in every market.

### Reason for Submission

This site has a very unique and bold design. Also, Rapyd is a notable company in the fintech industry.

**Comment by lorenzo6992** [comment]
Ciao a tutti! Here a little text for Rapyd

Rapyd is a leading company in the global payment solutions sector, offering an innovative platform to simplify and accelerate financial transactions worldwide. With a focus on seamless integration, Rapyd enables businesses of all sizes to accept payments and manage cash flows efficiently and securely.

Rapyd chose WordPress as their CMS because its high level of customizability allows them to create a professional and innovative user interface, ensuring a top-notch user experience. Thanks to WordPress's flexibility and customization options, Rapyd developed an intuitive and modern website that reflects their mission of innovation and reliability in the payment industry.

**Comment by marko-srb** [comment]
I don't think this site looks like a perfect match for Showcase, but in case we move forward with it, here are the screenshots...

![www rapyd net_(iPhone SE)](https://github.com/WordPress/Marketing-Team/assets/111751264/07727d45-f6c9-4f16-b697-74821cf91789)
![www rapyd net_(Screenshot Tool) (1)](https://github.com/WordPress/Marketing-Team/assets/111751264/7c4b6b09-6def-401f-b68b-1e417282c60c)

**Comment by thetinyl** [comment]
> I don't think this site looks like a perfect match for Showcase

I agree with @marko-srb here. Let's pass for now and we can revisit in the future.
