### ISSUE TITLE
GrowYourStory WordPress campaign (2022 launch)

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#51]
New campaign launched 1 April 2022.

[Launch post](https://make.wordpress.org/marketing/2022/04/01/grow-your-story-on-wordpress/)

[Form for submissions](https://docs.google.com/forms/d/e/1FAIpQLSd3uAVjqsfiiycVBJOwrpGJQuJZaRI11lpan8KIArgQhcCZKw/viewform)

Contact for this campaign: Jonathan Pantani @jpantani

Reference to Matt Mullenweg asking 'how has WordPress helped grow your story?' at the [2021 State of the Word](https://youtu.be/OpiH_P9aGhQ?t=3383),

**Comment by jpantani** [comment]
With the new post being published, we will finally begin pointing to it from all social media posts supporting the campaign beginning the week of 11 April. Currently, one post per week is sent out on the 4 major social platforms for WordPress.org (FB, IG, LI, & Tw).

**Comment by jpantani** [comment]
Update 18 April: As an inaugural brand campaign (or first in a while at least) Grow Your Story resides in an ecosystem where “updates” and “news” reign supreme. However, the campaign continues onwards with weekly posts, and it makes up about 8.5% of our tagged social posts.
Best engagement occurs on Twitter while by platform the campaign enjoys high ranks of engagement on Instagram among all the content/posts.
It appears the best performing copy is on Twitter as well as it’s bit playful/lighthearted about what you can do on Twitter vs. WordPress. Examples:

- When your perspective needs a little more than a couple hundred characters
- Storytelling in as many characters as you’d like since 2003
- When your voice deserves more than a chirp

The initial post has proven the campaign’s most popular inferring that something about that 1st week’s post resonated as something interesting to our audiences either visually, verbally, or both. https://twitter.com/WordPress/status/1496510169676713990

**Comment by murillol** [comment]
@jpantani are there any plans to translate the campaign into Spanish (and other languages)?

**Comment by jpantani** [comment]
@murillol that's great idea as the campaign evolves. I think it might be worth taking a look at this performance and making tweaks before doing so. Also I would love help/guidance in working with polyglots because I'm not familiar with that process.

**Comment by murillol** [comment]
Cool @jpantani I think a good way would be to join in the #polyglots weekly Slack chat on Wednesdays, and drop in the request/question there, and they'll be happy to tell us how to proceed!

**Comment by jpantani** [comment]
No major updates this week.
During the team meeting @nalininsbs can we please make a call directly to those on the make marketing team to share their stories. It would be great to start from our own group before looking outside of our group for participation. Thank you!

**Comment by murillol** [comment]
hi @jpantani ! we're still encouraging marketing contributors to share their own stories, besides that do we have an update for this week? or maybe an initial goal we want to reach (like 100 submissions or something like that) so we can gamify it a little?

**Comment by murillol** [comment]
> hi @jpantani ! we're still encouraging marketing contributors to share their own stories, besides that do we have an update for this week? or maybe an initial goal we want to reach (like 100 submissions or something like that) so we can gamify it a little?

Checking in @jpantani :-)

**Comment by jpantani** [comment]
Hi @murillol Yes, sorry I missed the original message so thank you for bringing it back to the top of mind. 
I continue to work the campaign with weekly content. 
Right now, we still have just a handful of submissions. 
The big update is that we will make submissions to the grow your story a part of contributor day so people can talk about their experiences. 
(Honestly, I would be happy with 50 submissions right now!)

**Comment by jpantani** [comment]
We had just 1 contribution during contributor day to the Grow Your Story campaign, although when explained the idea resonates strongly across a diverse group of people. 
I ask every member of the Marketing team to share how WordPress, WordCamps and other related activities has helped them in their lives, careers, publishing, blogging, website creation etc. to complete this form and discuss the opportunities they got from WordPress:
https://make.wordpress.org/marketing/2022/04/01/grow-your-story-on-wordpress/
We make WordPress look good by making its users seem both relatable and remarkable! :) 
I will be away from keyboard from 6/6 to 17/6 and have content queued for each of the weeks I am away.
I look forward to seeing a number of new submissions upon my return. 
Thank you all for your continued collaboration and support. Next translating the campaign

**Comment by murillol** [comment]
hi @jpantani! any updates for this campaign? I was thinking that plenty of people contributed to the [https://wp19.day/](https://wp19.day/) initiative and maybe we could reach out to some of them directly so they can fill out the form? (since we know they're comfortable sharing testimonials publicly)

**Comment by murillol** [comment]
> hi @jpantani! any updates for this campaign? I was thinking that plenty of people contributed to the https://wp19.day/ initiative and maybe we could reach out to some of them directly so they can fill out the form? (since we know they're comfortable sharing testimonials publicly)

Checking in @jpantani ;)

**Comment by jpantani** [comment]
Hi @murillol No major updates for the campaign. Sorry about the delay in updates here.  Here is what's new:
I've noticed that engagement seems to be a bit higher when linked to Community (WordCamps) so tying to similar initiatives will be great. I've also seemed to notice a bit better engagement when they're less frequent. Kind of like a small reminder of "Hey WordPress fam., we see you and hear you. We'd love for you to tell us your [WordPress] story." 
We've had a total of 11 submissions, not many but there are a few good testimonials. 
Let's see if we can get this to Polyglots soon.

**Comment by murillol** [comment]
Hi! Is this campaign still ongoing @jpantani ?

**Comment by murillol** [comment]
hi! I'd love to know what's going on with this. It's something I'd like to be more involved with but I'm not clear on the status! Is it something I could bring up on the next Open Floor? Any pointers @santanainniss?

**Comment by jpantani** [comment]
Hi @murillol  must have missed your last post from during the holidays. The current status of the project is on pause as I've been asked to focus my time on the 6.2 Release and the upcoming anniversary book. 

The good news is we have dozens and dozens of responses now because @DanSoschin included this in the annual survey. With these responses, it could be transformed into social media-sized snippets that were part of its original intent and to be featured on WordPress social media channels. @santanainniss would love to partner with you to bring this to a wider team audience who can help with it. We might need to open a new card to create a better home for this campaign as it will be entering a new phase.

**Comment by sereedmedia** [comment]
I sense a Contributor Day project!!

**Comment by santanainniss** [comment]
@jpantani  We are just about to complete contributor day tasks for WC Asia tomorrow morning (your 6pm tonight haha!) and that would be a great opportunity to get some support. 

I hesitate to create a card myself, as I'm not completely up to speed on where folks can find the responses and what type of social snippets you have in mind. Do you have time between now and 4pm PT to create a new card? @sereedmedia can then add it to the Contributor Day documentation as I'll be sleeping! :)

**Comment by jpantani** [comment]
Sorry, I missed this @santanainniss and @sereedmedia for Contributor day. The day got away from me as we're deep in About Page work and more for 6.2. 

In any event, the responses require more than an afternoon's worth of cleanup so a new card wouldn't have been ready in time. I think this is the ideal type of work for the team and can focus more in the coming weeks as the major prep work for 6.2 quiets down.

**Comment by jpantani** [comment]
@murillol nomad-skateboarding-dev Are you interested in partnering to work on this project with me in the coming weeks? I envision being able to look at some of the stories that have been collected and ready them for social media? I think it's a great brand play for WordPress to tell community member stories as part of its effort to reach new users (and secretly act as a love letter to the community for all its given folks) If so we we can figure out how to work on this together. Could definitely use the help if it's to be revived!

**Comment by murillol** [comment]
Hi @jpantani! Yes I am interested 👍

**Comment by jpantani** [comment]
@murillol 6.2 is out in the world (phew!) So I am coming back to Grow Your Story now. 
I'm adding a redacted list of comments about how WordPress has affected individuals' lives. 
https://docs.google.com/spreadsheets/d/12lOm5_9FnV60fMm_ZmTTZyfXQLtwl_Q33RTAFNNSym4/edit#gid=1996791536
It would be great to start taking sections and editing them into snippets (that we can turn into "social media-sized sound bites."
Would you want to select some you think might be good? Those can be added in Columns L, M, N

**Comment by jpantani** [comment]
[Grow Your Story Phase II](https://github.com/WordPress/Marketing-Team/issues/222) ticket opened.
Please come over to the new issue!
