### ISSUE TITLE
Discussion: Updating the Marketing team description

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#87]
Discussion on updating / revising the descriptor of the team that appears in the Marketing Team Handbook.

**Current descriptor**
The Marketing team focuses on making WordPress marketable in all sorts of contexts, from the [WordPress.org](http://wordpress.org/) side all the way to core and the wider community. We market WordPress and its community to the wider world.

6 July 2022: Discussion in Slack https://wordpress.slack.com/archives/C0GKJ7TFA/p1657121780284969

13 July 2022: Discussion in Slack

**Comment by nalininsbs** [comment]
@eidolonnight could you please add a link and summary from the two meeting this has been discussed at. I added this card as a reference to today's agenda to invite people to add suggestions. Thank you Nicholas.
---
Contributors coming to this card, please add suggestions directly to this card. You only need a GitHub account to do this. Thank you in advance.

**Comment by thetinyl** [comment]
I've been thinking about this a bit since it first came up. Looking through some of the feedback from the previous Slack discussions linked above, plus taking a tour around what other teams have done to get a baseline, I've drafted some words for consideration. 

### A quick observation about the Marketing description
I noticed that the Marketing description on the "Get Involved" page is different from what's noted above in the Welcome Box/Handbook. This doesn't seem to be the case for most other teams.

The trend appears to be:

- On the 'Get Involved' page: One/two lines about the general purpose of the team within WordPress
- In the Welcome Box/Handbook: The same or slightly adjusted one/two lines with a bit of an expanded description that adds more details. 

I looked at a few different teams, but some of the ones that stood out as examples were Documentation, Accessibility, and Design (if others wanted to take a look).

### Copy suggestions for the "Get Involved" page

<img width="485" alt="Screen Shot of Marketing team description on the Get Involved page" src="https://user-images.githubusercontent.com/100625704/183738778-eb79515c-0934-4a9d-a153-9b1d4613731f.png">

Here are a few variations I've been playing with:

>**Option 1:** The Marketing team supports the growth of the WordPress Project. From helping other teams share their programs and initiatives, to showcasing the power of the platform and community to current and future users, extenders, and contributors.

> **Option 2:** The Marketing team supports the growth and maintenance of the WordPress Project. From helping other teams share their programs and initiatives, to showcasing the power of the platform and community to current and future users, extenders, and contributors.

> **Option 3:** The Marketing team supports the growth of the WordPress Project. From helping other teams share their programs and initiatives, to highlighting the benefits of the platform and community for current and future users, extenders, and contributors.

### Copy suggestions for the Welcome Box/Handbook

<img width="673" alt="Screen Shot of Marketing team description in the Welcome Box" src="https://user-images.githubusercontent.com/100625704/183739048-8e60e1f6-e921-4f10-9fb8-764f83088206.png">

I'd propose using whichever option above feels the most accurate, then adding a section to expand into more specifics (for the following example, I'm using Option 1 from above):

> The Marketing team supports the growth of the WordPress Project. From helping other teams share their programs and initiatives, to showcasing the power of the platform and community to current and future users, extenders, and contributors.
>
> The team contributes to marketing efforts across the WordPress ecosystem, including communications strategy and planning, media relations, social media management, brand building, and content creation. 

Looking forward to seeing what people think! 😃

**Comment by eidolonnight** [comment]
As I said in Slack, I think that our existing descriptions could maybe be better. For example, we market WordPress to the wider world, but also to the people already within the WordPress ecosystem. We could probably be more specific about _what_ we market too. For example, we don’t market specific themes or plugins for individuals/companies. Our focus is on features, programs, and efforts that are core to the project.

Thank you @thetinyl for some initial explorations here.

> The Marketing team supports the growth and maintenance of the WordPress project. From helping other teams share their programs and initiatives, to showcasing the power of the platform and community to current and future users, extenders, and contributors.

I really like "supports the growth and maintenance" as it touches on the fact that we are both growing our audience as well as performing important maintenance work that supports the project. I also love that you spell out "current and future users, extenders, and contributors." so our audience is clearly defined.

> From helping other teams share their programs and initiatives, to showcasing the power of the platform and community

I think there is some room for improvement in this line though. The "from this to this" is a bit too broad to be useful, but also specific enough to be limiting. It might make more sense to get at the heart of what marketing does. I see that as developing, executing, and monitoring programs and campaigns that promote the use and development of WordPress. We are not just a resource for strategy. We take action and are accountable for those actions (Ie. we monitor the results). We're not only showcasing content from other teams, we are _creating_ content.

The specifics of this can then be expanded in our welcome box with the other line from above, which may change with some regularity as our projects change.

So I'm thinking something like the following:

> The Marketing team develops, executes, and monitors programs and campaigns that promote the growth and maintenance of the WordPress project to current and future users, extenders, and contributors.

**Comment by rmartinezduque** [comment]
Thanks for thinking about this and starting to draft some words, @thetinyl!

Of the three options above, the second one seems to me to be the most accurate. However, I like @eidolonnight's suggestion to get to the heart of what marketing does and to include the specifics in the welcome box.

I also wonder if, besides including the expanded description in the welcome box, we can provide a little more clarity on the relevant resources/links to new visitors and contributors. That is, where they learn more about what the Marketing team does, the current projects, and how to collaborate. Maybe it's a bit long but, for example, I like how the [Documentation team](https://make.wordpress.org/docs/) also provides an overview of the most important resources.

This is just a suggestion that I think can complement and improve the effort to improve the description of the team. I understand if it goes a bit outside the scope of this task though. 🙂

**Comment by sereedmedia** [comment]
I like this for its succinctness:

> The Marketing team develops, executes, and monitors programs and campaigns that promote the growth and maintenance of the WordPress project to current and future users, extenders, and contributors.

However, I am missing the presence of the community in this, which was present in some earlier iterations. One could argue that "the WordPress project" as a whole encompasses the community, but in my experience/IMO most people think of the project as the software and the community as the people. I liked the differentiation between platform and community for this reason. Additionally, specifying "the platform" emphasizes the narrower scope of the core platform, and not the wider ecosystem.

So perhaps expanding on that, with a few tweaks back to previous language (changes bolded):

The Marketing team **creates**, executes, and monitors programs and campaigns that **support** the growth and **development** of the WordPress ****platform and community and promote the WordPress project** to current and future users, extenders, and contributors.



Note, this would also serve as a good litmus test for making marketing decisions in the future:
1) Does it support the growth and development of the WordPress platform and community?
2) Does it promote the WordPress project to current and future users, extenders, and contributors?

**Comment by eidolonnight** [comment]
> However, I am missing the presence of the community in this, which was present in some earlier iterations. One could argue that "the WordPress project" as a whole encompasses the community, but in my experience/IMO most people think of the project as the software and the community as the people.

This is interesting. Thanks @sereedmedia . I was indeed considering the community as part of the WordPress project.

> Note, this would also serve as a good litmus test for making marketing decisions in the future:
>
> 1. Does it support the growth and development of the WordPress platform and community?
> 2. Does it promote the WordPress project to current and future users, extenders, and contributors?

I do not think we should use pint 1 as a litmus test, but we have in the past. The problem is that this quickly becomes too broad. In the last few months we've seen requests to promote individual plugins, corporate events, publications, etc. Would helping a theme author, a member of the WordPress community, promote their theme, pass that litmus test? Many people seem to think so, and I understand their confusion. That is however not this team's purpose. Expanding on the example above, we may promote WordPress _to_ theme authors and share things like calls for testing from the Themes team. We would _not_ help promote an individual author's theme. On top of it not being a part of our purpose, it's far too difficult to do equitably.

This is why I had trouble explicitly using "community" in any of my drafts. We do promote the community, but only within the confines of the project.

**Comment by santanainniss** [comment]
> but in my experience/IMO most people think of the project as the software and the community as the people 
@sereedmedia I head this expressed a lot at the Marketing table I led at contributor day at WCEU. And also that many didn't know that there even was a community of people supporting the software. So I love the idea of naming the community specifically! 

@thetinyl Thanks for sharing drafts on this. I especially resonated with the handbook copy

"The WordPress marketing Team markets WordPress and its community to the wider world. 1. I love alliteration in marketing copy; studies show it aids in recall!  2. To the point, clear, punchy. 

I think my favorite option shared was no. 3 

> The Marketing team supports the growth of the WordPress Project. From helping other teams share their programs and initiatives, to highlighting the benefits of the platform and community for current and future users, extenders, and contributors.

But wonder how to bridge the gap between that and Sé's comment above. Perhaps something like 

_The Marketing team supports the growth of the WordPress  **open source** Project  and **its community.** From helping other teams share their programs and initiatives, to highlighting the benefits of the platform and community for current and future users, extenders, and contributors._

**Comment by thetinyl** [comment]
Personally, I'm torn between @eidolonnight's suggestion and @sereedmedia's variation that solves for the "community" often being missed despite being implied. 

I'd be happy to throw my vote behind either. 

For @eidolonnight's version, I do think my preference would be for Sé's word choice: "creates" over "develops", and "development" over "maintenance". I'd also consider the following change in bold, just to cut down on words a bit further:

> The Marketing team creates, executes, and monitors **initiatives** that promote the growth and development of the WordPress project to current and future users, extenders, and contributors. 

For @sereedmedia's version, I'd also suggest the same word change as above, plus adding punctuation to break up the long sentence (changes in bold):

> The Marketing team creates, executes, and monitors **initiatives** that support the growth and development of the WordPress platform and **community; to** promote the WordPress project to current and future users, extenders, and contributors. 

_As an aside:_ I also agree with @rmartinezduque's idea about expanding the Welcome Box further to link off to relevant resources. Is that something we should open another Github issue about (once this one closes)? Or continue discussing here?

**Comment by jpantani** [comment]
> to promote the WordPress project to current and future users, extenders, and contributors.

If we add platform and community, which are specific to WordPress, we might want to edit the last part for brevity adjusting it to **existing and future audiences** rather than "current and future users, extenders, and contributors." 

But in reading the newer comments especially from @sereedmedia if there is a perception problem of the project being platform(software) and community(people) that means there is a miss somewhere in what the project is.  I would venture a guess that if/when we use the word project we'd like for people to associate it with both things, and we have a first chance to amend that with some of the revised copy.

**Comment by nalininsbs** [comment]
@eidolonnight has shared today that it is the last week to add any feedback to this discussion. It will then go to Josepha for consideration. Please add your comments.

**Comment by thetinyl** [comment]
> I'm not totally against swapping "programs and campaigns" with "initiatives", but it does seem like a missed opportunity for further clarity and the introduction of marketing terms. Could you elaborate on the word choice here?

@eidolonnight That's an interesting perspective. Primarily, it felt like a sentence full of lists, and that made it a bit cumbersome to read. Out of all the places to be a little less specific, that felt like it would impact the message the least. 

I do think it's okay to be a little all-encompassing, given the rest of the message feels focused and clear. However, if "initiatives" does feel too vague, I'd still suggest sticking to one word. If we're talking marketing terms, "campaigns" feels much more obviously marketing-y than "programs" (which exist elsewhere in the community).

Also thinking about where this description will live (likely in 3 places: Make page, Welcome Box, Handbook), it will have additional content for context most of the time.

**Comment by nalininsbs** [comment]
@eidolonnight is there an update on this issue please or do you have a preferred date when we could come back to it? Thank you.

**Comment by sereedmedia** [comment]
In my experience, "community" does not at all imply plugins or themes, that is usually covered by the term "WordPress ecosystem". But if it's too controversial to say community, then I like the line that @murillol referenced above:

> The Marketing team creates, executes, and monitors initiatives that promote the growth and development of the WordPress project to current and future users, extenders, and contributors.

However, I think that extenders are users, and technically, so are developers. "End-users" are the actual "users" we are differentiating between here. I don't think extenders is understood enough in parlance to be useful. Also "contributors" could be interpreted to mean the community (see FFTF discussion) and folks who contribute to the ecosystem, so I think that covers developers as well. 

I also like "initiatives" because it allows for a variety of ways for the Marketing team to accomplish its goals.

So and thus, I like this slightly streamlined version:

**The Marketing team creates, executes, and monitors initiatives that promote the growth and development of the WordPress project to current and future users and contributors.**

**Comment by murillol** [comment]
> I don't think extenders is understood enough in parlance to be useful.

Agree..

> The Marketing team creates, executes, and monitors initiatives that promote the growth and development of the WordPress project to current and future users and contributors.

I like this one too!

**Comment by sereedmedia** [comment]
What is the timeline for this discussion and eventual adoption?

**Comment by nalininsbs** [comment]
When this is updated. Can the update be added to this page of the Handbook too.  Thank you. https://make.wordpress.org/marketing/handbook/about/
The link to the Slack channel has been added to this page today.

**Comment by eidolonnight** [comment]
> The Marketing team creates, executes, and monitors initiatives that promote the growth and development of the WordPress project to current and future users and contributors.

Looks good to me. "Initiatives" still doesn't feel like the right word to me, but I'm happy if everyone else is happy. With the introduction of our new team reps, I'm going to update the assignees for this issue. I believe the next steps are:

1. Consult Josepha (probably in the #team-reps channel would be best) to ensure that the new description is also in alignment with her expectations for the team. I believe that I communicated the reasons for this change in my earlier comments, but am happy to be tagged in anywhere to discuss more.
2. Update the https://make.wordpress.org/  snippet - Unsure who has access. Consult Meta.
3. Update the [welcome box](https://make.wordpress.org/marketing/welcome/) - New reps should all have proper edit access to this page.
4. Update the [handbook](https://make.wordpress.org/marketing/handbook/about/) - New reps should all have proper edit access to this page.

**Comment by santanainniss** [comment]
Final call for contribution to this discussion! All comments/ideas/concerns etc are welcome before 26 January 2023. After this point, team reps will review and consolidate the discussion and move forward with the new team description according to the steps outline by @eidolonnight above.

**Comment by santanainniss** [comment]
Thank you to all the contributors on this thread. Creating a team description that represents our work is important, and there has been a lot of great dialog and contribution on this GH issue. After issuing the last call for contribution, Team Reps reviewed the complete thread and discussed all that contributions that were shared. 

With that said, we have finalized the proposal for an updated team 

> _The Marketing team creates, executes, and monitors initiatives that promote the growth and development of the WordPress project to current and future users and contributors._


Our next steps are as follows:

1. Consult with Josepha in the Team Reps channel in Slack.
2. Review Josepha's feedback. If there are no major edits we will move forward to step 3. If there are major edits required, we will open a new GH issue for transparency and open collaboration
3. Update the make.wordpress.org snipped
4. Update the welcome box
5. Update the handbook

Thank you again to everyone that contributed to this conversation. <3

**Comment by nalininsbs** [comment]
Hello, apologies. I have opened this card and saw my contribution was still sat in the draft. 

My additional thoughts for reflection.

- explaining more what “extenders” are especially in relation to “contributors”. This may not be as clear to our general audience
- being clear on what the opportunities will be so people do not have a different or higher level of expectations of what is possible in open source/ WordPress, how collaborative approaches work. Should we review the final description against what the average contributor will be able to influence, take part in, etc.


- add something about 'increases understanding' of the software, community. I do not think this is under the description I have seen so far. Possibly even, in extension, open source opportunities and how it can be transformative. Some of the marketing team's work I have seen over time and now also achieves these things.
- not sure if this covers the information aspect - informing people about WordPress and its community too? The social media, the articles, campaigns all do this too.

**Comment by santanainniss** [comment]
Thank you so much for sharing your draft and thoughts with us @nalininsbs. I definitely hear your perspective and value the time you took to share this. We did a last call for contribution so I will leave the issue closed for now to be fair to the group and help keep the forward momentum.
