### ISSUE TITLE
WordCamp US 2022 Marketing Table - Contributor Day

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#90]
Card for all things related to preparation for WordCamp US 2022 Contributor Day's Marketing Table. If you are organizing items for this, have suggestions, creating resources or documents, please add them to this card. Thank you.

WordCamp US is in September 2022.

**Comment by nalininsbs** [comment]
**Update being shared at 20 July 2022 Marketing Meeting**
@eidolonnight: With WordCamp US approaching in September, it would be nice to start a list of who plans to attend. General admission [tickets went on sale on June 30th](https://us.wordcamp.org/2022/wcus-tickets-on-sale-soon/) and have already sold out. If you couldn’t get yours, the organizing team recommends [checking the site](https://us.wordcamp.org/2022/tickets/) periodically to see if any become available.

Julia Golomb is [requesting that we submit our Table Lead(s), Table Onboarder, and Team Slack Rep by July 29](https://make.wordpress.org/community/2022/07/07/wcus2022-contributor-team-signup/) (I will complete the form for our team). We have about 40 registrants expressing interest in Marketing on Contributor Day, so any help here is very welcome. You’ll notice that the “Slack Rep” does not need to be at WCUS in-person.

Table Leads: Table leads will be helping direct traffic – welcoming folks to the table and pointing them to various tables for projects or table onboarding. We recommend larger teams have at least two Table Leads.
Team Onboarder (Optional): Ideally, we would like to see each table have someone who will take responsibility for onboarding new contributors. While some teams might do this at the beginning of the day, new contributors might show up later.
Team Slack Rep (Optional): This person can be at WCUS in person or online remotely. They would be responsible for helping out folks in Slack by answering questions or helping folks who are participating remotely get started.

If you got your ticket and plan to attend specifically for contributor day, please let us know in this thread! Also let us know if you would like to volunteer for one of the roles above.

**Comment by nalininsbs** [comment]
A number of people have volunteered to help async and in person. Please do add your details to this card too.

**Comment by jpantani** [comment]
I will be at WCUS and help as a table lead. I believe @DanSoschin will also be there in that capacity (he's AFK this week and I want to ensure we are able to get back to Julia on time)

**Comment by nalininsbs** [comment]
@eidolonnight was to submit an update I believe to Julia after last week's Marketing meeting.

**Comment by nalininsbs** [comment]
We will need to recruit more contributors available to help new contributors with using slack on the day. Will there be a dedicated table to help setting up accounts at the event too?

**Comment by eidolonnight** [comment]
Current attendee list from Slack:
- [@Ali Parisi (she/her)](https://wordpress.slack.com/team/U03N2GGRF46)
- [@Ali-WPFiddlyBits](https://wordpress.slack.com/team/UFXDM6F1Q)
- [@sereedmedia](https://wordpress.slack.com/team/U41M20MKL)

**Comment by nalininsbs** [comment]
The Contributor Day will be on Sunday September 11, 2022. https://us.wordcamp.org/2022/schedule/

**Comment by eidolonnight** [comment]
Added Drive folder for WCUS 2022 and doc for planning: https://docs.google.com/document/d/1qpVCYmzFNjgp1HitUqT6byFTKmjSm38oyTF0yoeR2nw/edit#

**Comment by nalininsbs** [comment]
Collaboration session after last week's team meeting. Attended: @eidolonnight , @jpantani , @nalininsbs , @DanSoschin , @webcommsat.

Many useful ideas. Document in Nicholas' message above was updated. Discussion on the items which could be done in the time. @eidolonnight is there anything else needed? WCUS have also posted a [query](https://wordpress.slack.com/archives/C0GKJ7TFA/p1661278775759549) if we need anything further in the Slack channel. 

Thank you everyone for your contributions so far.

**Comment by sereedmedia** [comment]
I think this: [(https://make.wordpress.org/meta/2022/08/18/navigation/](https://make.wordpress.org/meta/2022/08/18/navigation/)

would be a great discussion to have in person on contributor day. 

perhaps with the goal of creating a proposal to put on Make.

I am not sure if i'm able to go to Contributor Day yet, but this is the type of thing a discussion could really streamline.

**Comment by abhansnuk** [comment]
Linking up the above request with [more detail on the request from Meta](https://github.com/WordPress/Marketing-Team/issues/106#issuecomment-1226421899) on next week's meeting card.

**Comment by nalininsbs** [comment]
@eidolonnight could you copy the update you shared on the outcome to this card please? It will be a good reference for next year and for others wanting to attend or help with similar events. Thank you.

**Comment by murillol** [comment]
Are you referring to the updates shared in [these Slack messages](https://wordpress.slack.com/archives/C0GKJ7TFA/p1663773062742489)? I wasn't at this meeting and am not sure @nalininsbs

**Comment by abhansnuk** [comment]
Summarizing the Slack so we can close this ticket.

Input on the the following tasks at WCUS 2022 Contributor Day (the IDs below are the ones shared in Slack by Nicholas):
- [Five for the Future Email Template for Contributors](https://github.com/WordPress/Marcomms-Rolling-tasks/issues/18) 
- [Create plan for short-form video content on Tiktok](https://github.com/WordPress/Marketing-Team/issues/114) (Github issue 114) has been something a few people have been interested in since we reclaimed out Tiktok account. At WCUS, 
[@Matthew1551](https://wordpress.slack.com/team/U03FU93M5UH)
, @craylor, and @jmchannell [put together some wonderful thoughts on the how this can be done](https://docs.google.com/document/d/1PgCn3fl3aydTL8CPTbMoIorA2wa4iDzsmYivpgSCwYs/edit#). Let’s discuss next steps in the [GitHub issue](https://github.com/WordPress/Marketing-Team/issues/114) and put together some pilot content.
More on this update at [Slack message](https://wordpress.slack.com/archives/C0GKJ7TFA/p1663773160465129).
- [Several ideas come in](https://docs.google.com/spreadsheets/d/1zwr3aaNmLreFpYJssohPWt1JwtAyvLNxl6sYdVdtmt8/edit#gid=0) for the #WordPress, #WPPhotos, #LearnWP, #WPOpenverse, #GrowYourStoryWP, and #WordCamp campaigns during WCUS Contributor Day. I’ve updated the [WordPress Social Media Amplification](https://github.com/WordPress/Marketing-Team/issues/7) (Github issue 7)  issue.
- [Open brainstorming doc from WCUS with several ideas](https://docs.google.com/document/d/1y_Z_oytdkuwtag6Wa7D1b61KGT9u3XnbYGAYqGeNSfE/edit#heading=h.fakclxs6n8du). Note: a GitHub card has not been created for this, @eidolonnight has left it open for contributors to review and create issues as needed.

**Comment by sereedmedia** [comment]
I've moved the links shared to the WCAsia 2023 card: https://github.com/WordPress/Marketing-Team/issues/108

Closing this issue as WCUS 2022 is done and gone!
