### ISSUE TITLE
2022/8/3 Marketing Team meeting

### ISSUE THREAD

**Issue by nalininsbs** [WordPress/Marketing-Team#94]
All things related to this meeting and any collaborations during the week, including:

- planning
- suggestions for items and agenda drafting, including suggesting items for Open Floor
- check the [diary dates post](https://make.wordpress.org/marketing/2021/01/13/forthcoming-diary-dates/) has been updated
any asynchronous update on tasks
- script to assist the running of the meeting
- queries about notes drafting
- links to draft notes and published post
- other Make Teams can also add items for awareness at a future meeting to this card
- collaboration planning/ resources
- any updates to the team Google calendar on planned collaborations

**Useful links:**
[Marketing Tasks board](https://github.com/orgs/WordPress/projects/21)

[Marketing Team coffee break](https://github.com/WordPress/Marketing-Team/issues/23)

**Comment by nalininsbs** [comment]
Agenda draft ](https://make.wordpress.org/marketing/?p=9642&preview=1&_ppp=51e71a9a81)in the Marketing Team blog to help with earlier publishing.

**Comment by thetinyl** [comment]
✋ I can take notes for this meeting (Aug 3)!

**Comment by thetinyl** [comment]
Hi all! 

The [draft notes from the 3 August meeting](https://make.wordpress.org/marketing/?p=9681&preview=true) are ready for review. 

As it's my first time drafting notes, I had a couple of questions:

- @nalininsbs I was curious about the line at the top that says "Link to the start of the meeting on Marketing Slack to help with asynchronous contributions." It confused me at first, as I misinterpreted it as directions for the notetaker 😅. Particularly since we already link to the same place with a little more explanation directly below it. Wondering if there's more context available or if there's value in removing it to minimize repetition.
- My user ID is the only one underlined as I can't seem to tag myself in the P2 backend. Wondering if there's any way to fix this? (I tried both my updated .org ID and my previous one.)

And thank you @murillol for taking the time to look at my initial draft. I really appreciate the help and guidance!

**Comment by nalininsbs** [comment]
Thank you @thetinyl .

The link has moved to the welcome section and been retained at the top. We can lose one of these, I deleted the one at the top. I have edited it to be clear to those unfamiliar with Slack and the channels, as well as which Slack to use as there are many in WordPress. 
Eg. The meeting discussions on the [Marketing team channel](https://wordpress.slack.com/archives/C0GKJ7TFA/) can be found starting [at this timestamp](ADD LINK) link on the Make WordPress Slack to help anyone contributing asynchronously.

**Comment by murillol** [comment]
Ok I'm going to make that a separate to-do item @nalininsbs, as I've never edited the handbook and can't make the time to really explore it until the weekend. Perhaps Santana could also help with it when she gets back ;)

**Comment by nalininsbs** [comment]
@thetinyl I have added in the GitHub cards for the meeting notes, and changed the card link at the end to next week's meeting from the 17th. Added excerpt. 
@murillol anything to add from you?

**Comment by thetinyl** [comment]
Thank you @nalininsbs! 

Once @murillol has another look through, am I safe to hit publish?

**Comment by nalininsbs** [comment]
As Larissa has looked through these earlier too, I am going to publish the notes shortly. We can then link to them and publish the agenda to give people some time to see it before the meeting tomorrow. Thanks @thetinyl .

**Comment by nalininsbs** [comment]
Published: https://make.wordpress.org/marketing/2022/08/08/notes-global-marketing-team-meeting-august-3-2022/
